title: Minimizing Regret
logo: /assets/img/deluca.svg
description: Hazan Lab @ Princeton University
show_downloads: false
theme: jekyll-theme-minimal
authors: ["elad"]
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      tags: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      tags: false

